# ===============================
# ? APP CONFIGURATION
# ===============================
app.frontend.url=http://localhost:5173,http://192.168.29.73:5173,http://192.168.29.73:3000,http://localhost:3000,http://localhost:5174,http://192.168.29.73:5174,https://portfoliosbuilder.com,https://admin.portfoliosbuilder.com,https://www.portfoliosbuilder.com,https://*.portfoliosbuilder.com
app.url=https://admin.portfoliosbuilder.com/

# ===============================
# ? POSTGRESQL / NEON CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://ep-delicate-snow-ath6sfr9-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_bk0tChuzB3Ys&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_bk0tChuzB3Ys

# ===============================
# ? EMAIL CONFIGURATION (Gmail SMTP)
# ===============================
spring.mail.username=portfolio.splash@gmail.com
spring.mail.password=pbvq eqnp zgah htsh

# ===============================
# ? JWT CONFIGURATION
# ===============================
jwt.secret=t5I3NmBxUb/0B/qzqIGVnCWFj9DKXhioRIvRQTOQRXA=
jwt.access-token.expiration=36000000

# ===============================
# ? CLOUDINARY CONFIGURATION
# ===============================
cloudinary.cloud-name=dns4kwhz5
cloudinary.api-key=414413168634356
cloudinary.api-secret=eht-y_YuyCwQXsYm65iaidwsdzc

# ===============================
# ? RESEND CONFIGURATION
# ===============================
resend.api.key=re_RGzmKBXs_PXWwNGtjps9je9zbi23KfWQt
resend.from-email=no-reply@portfoliosbuilder.com
