CREATE TABLE profiles (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    about_me TEXT,
    about_me_image_public_id VARCHAR(255),
    about_me_image_url VARCHAR(255),
    created_by VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    email_verified VARCHAR(255) CHECK (email_verified IN ('PENDING', 'VERIFIED')),
    full_name VARCHAR(255),
    location VARCHAR(255),
    logo_public_id VARCHAR(255),
    logo_url VARCHAR(255),
    password VARCHAR(255),
    phone VARCHAR(255) UNIQUE,
    phone_verified VARCHAR(255) CHECK (phone_verified IN ('PENDING', 'VERIFIED')),
    profile_image_public_id VARCHAR(255),
    profile_image_url VARCHAR(255),
    role_id BIGINT,
    status VARCHAR(255) CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'DELETED')),
    title VARCHAR(255),
    updated_by VARCHAR(255),
    user_name VARCHAR(255) UNIQUE
);
