ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_discoverable    BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS digest_email_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS digest_last_sent_at  TIMESTAMP;
