-- Redesign the 3 existing email templates onto one consistent, branded layout
-- (previously OTP/reset used a plain gold div layout; contact-us used a bare
-- table -- neither matched the product's actual emerald brand color, and
-- table-based layout renders far more reliably across email clients).

UPDATE notification_templates SET
    subject = 'Your Verification Code — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">Verify Your Email</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 24px">Use the code below to verify your email address. It expires in <strong>{{expiryMinutes}} minutes</strong>.</p><div style="text-align:center;margin:0 0 24px"><div style="display:inline-block;background:#ecfdf5;border:1.5px dashed #059669;border-radius:12px;padding:18px 36px"><span style="font-size:34px;font-weight:800;letter-spacing:10px;color:#047857">{{otp}}</span></div></div><p style="color:#9ca3af;font-size:13px;margin:0">Did not request this code? You can safely ignore this email.</p></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'OTP-VERIFICATION';

UPDATE notification_templates SET
    subject = 'Reset Your Password — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">Reset Your Password</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Hi <strong>{{name}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 24px">We received a request to reset your password. Click the button below to choose a new one.</p><div style="text-align:center;margin:0 0 28px"><a href="{{resetLink}}" style="display:inline-block;background:#059669;color:#ffffff;text-decoration:none;padding:14px 32px;border-radius:10px;font-weight:700;font-size:15px">Reset Password</a></div><p style="color:#6b7280;font-size:13px;margin:0 0 4px">Button not working? Paste this link into your browser:</p><p style="font-size:13px;word-break:break-all;margin:0 0 20px"><a href="{{resetLink}}" style="color:#059669">{{resetLink}}</a></p><p style="color:#9ca3af;font-size:13px;margin:0">This link expires in 30 minutes. Did not request this? You can safely ignore this email.</p></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'FORGOT-PASSWORD-TOKEN';

UPDATE notification_templates SET
    subject = 'New Message from {{senderName}} — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">New Portfolio Message</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Hi <strong>{{profileName}}</strong>, someone reached out through your portfolio contact form.</p><table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;font-size:14px"><tr><td style="padding:12px 16px;font-weight:600;color:#374151;background:#f9fafb;width:100px;border-bottom:1px solid #e5e7eb">From</td><td style="padding:12px 16px;color:#374151;border-bottom:1px solid #e5e7eb">{{senderName}}</td></tr><tr><td style="padding:12px 16px;font-weight:600;color:#374151;background:#f9fafb;border-bottom:1px solid #e5e7eb">Email</td><td style="padding:12px 16px;border-bottom:1px solid #e5e7eb"><a href="mailto:{{senderEmail}}" style="color:#059669">{{senderEmail}}</a></td></tr><tr><td style="padding:12px 16px;font-weight:600;color:#374151;background:#f9fafb;border-bottom:1px solid #e5e7eb">Phone</td><td style="padding:12px 16px;color:#374151;border-bottom:1px solid #e5e7eb">{{senderPhone}}</td></tr><tr><td style="padding:12px 16px;font-weight:600;color:#374151;background:#f9fafb;vertical-align:top">Message</td><td style="padding:12px 16px;color:#374151">{{message}}</td></tr></table></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">Sent via PortfoliosBuilder</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'CONTACT-US';

-- New templates, matching the same branded layout above

INSERT INTO notification_templates (template, subject, message_body, is_email, is_sms, is_whatsapp) VALUES
(
    'TESTIMONIAL-SUBMITTED',
    'New Testimonial Submitted — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">New Testimonial Received</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 8px">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px"><strong>{{requesterName}}</strong> just submitted a testimonial for your portfolio.</p><div style="background:#f9fafb;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 28px"><p style="color:#374151;font-size:14px;font-style:italic;margin:0">"{{message}}"</p></div><div style="text-align:center"><a href="https://admin.portfoliosbuilder.com/testimonials" style="display:inline-block;background:#059669;color:#ffffff;text-decoration:none;padding:13px 30px;border-radius:10px;font-weight:700;font-size:14px">Review Testimonial</a></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">Log in to your admin panel to approve or reject this testimonial.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'PASSWORD-CHANGED',
    'Your Password Was Changed — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">Password Changed</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px">This is a confirmation that your PortfoliosBuilder password was changed on <strong>{{changedAt}}</strong>.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;border-radius:8px;padding:16px 20px;margin:0"><p style="color:#7f1d1d;font-size:13px;margin:0">If you did not make this change, reset your password immediately and contact support.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'WEEKLY-DIGEST',
    'Your Portfolio — Weekly Summary',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">WEEKLY PORTFOLIO DIGEST</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">Hi, {{fullName}}</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 24px">Here is what happened on your portfolio this week:</p><table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 28px"><tr><td width="48%" style="padding:18px;text-align:center;background:#f9fafb;border-radius:10px;border:1px solid #e5e7eb"><p style="font-size:30px;font-weight:800;color:#059669;margin:0">{{viewsThisWeek}}</p><p style="font-size:13px;color:#6b7280;margin:4px 0 0">Portfolio Views</p></td><td width="4%">&nbsp;</td><td width="48%" style="padding:18px;text-align:center;background:#f9fafb;border-radius:10px;border:1px solid #e5e7eb"><p style="font-size:30px;font-weight:800;color:#059669;margin:0">{{newMessages}}</p><p style="font-size:13px;color:#6b7280;margin:4px 0 0">New Messages</p></td></tr></table><h3 style="font-size:14px;color:#374151;margin:0 0 12px">Top Traffic Sources</h3><table width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid #e5e7eb">{{topReferrersHtml}}</table></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">To stop receiving these emails, turn off Weekly Digest in your admin profile settings.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'CONTACT-REPLY',
    'Re: Your message to {{profileName}} — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">You Have a Reply</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Hi <strong>{{contactName}}</strong>, <strong>{{profileName}}</strong> replied to your message.</p><div style="background:#ecfdf5;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 24px"><p style="color:#065f46;font-size:14px;line-height:1.6;white-space:pre-wrap;margin:0">{{replyMessage}}</p></div><p style="color:#9ca3af;font-size:11px;text-transform:uppercase;letter-spacing:1px;margin:0 0 8px">Your original message</p><p style="color:#6b7280;font-size:13px;line-height:1.6;white-space:pre-wrap;margin:0">{{originalMessage}}</p></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">Sent via PortfoliosBuilder</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'WELCOME-EMAIL',
    'Welcome to PortfoliosBuilder, {{fullName}}!',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">Welcome, {{fullName}}</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Your email is verified and your account is ready to go.</p><p style="color:#374151;font-size:15px;margin:0 0 24px">Here is what to do next:</p><table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 28px"><tr><td style="padding:10px 0;color:#374151;font-size:14px">1. Add your experience, skills, and projects</td></tr><tr><td style="padding:10px 0;color:#374151;font-size:14px;border-top:1px solid #f3f4f6">2. Pick a theme that matches your style</td></tr><tr><td style="padding:10px 0;color:#374151;font-size:14px;border-top:1px solid #f3f4f6">3. Publish and share your portfolio link</td></tr></table><div style="text-align:center"><a href="https://admin.portfoliosbuilder.com/dashboard" style="display:inline-block;background:#059669;color:#ffffff;text-decoration:none;padding:13px 30px;border-radius:10px;font-weight:700;font-size:14px">Go to Dashboard</a></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'TWO-FACTOR-ENABLED',
    'Two-Factor Authentication Enabled — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">2FA Enabled</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px">Two-factor authentication was just turned on for your account. You will now need an authenticator code every time you sign in.</p><div style="background:#ecfdf5;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0"><p style="color:#065f46;font-size:13px;margin:0">If you did not make this change, contact support immediately.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'TWO-FACTOR-DISABLED',
    'Two-Factor Authentication Disabled — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">2FA Disabled</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px">Two-factor authentication was just turned off for your account. Your account is less secure without it.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;border-radius:8px;padding:16px 20px;margin:0"><p style="color:#7f1d1d;font-size:13px;margin:0">If you did not make this change, contact support immediately.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'EMAIL-CHANGED',
    'Your Account Email Was Changed — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:32px;text-align:center"><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:22px;margin:0;font-weight:800">Email Address Changed</h1></td></tr><tr><td style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px">Your account email was changed to <strong>{{newEmail}}</strong>. You are receiving this at your previous address as a security notice.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;border-radius:8px;padding:16px 20px;margin:0"><p style="color:#7f1d1d;font-size:13px;margin:0">If you did not make this change, contact support immediately.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
);

-- TESTIMONIAL-SUBMITTED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'TESTIMONIAL-SUBMITTED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'requesterName', '{{requesterName}}', id FROM notification_templates WHERE template = 'TESTIMONIAL-SUBMITTED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'message', '{{message}}', id FROM notification_templates WHERE template = 'TESTIMONIAL-SUBMITTED';

-- PASSWORD-CHANGED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'PASSWORD-CHANGED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'changedAt', '{{changedAt}}', id FROM notification_templates WHERE template = 'PASSWORD-CHANGED';

-- WEEKLY-DIGEST variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'WEEKLY-DIGEST';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'viewsThisWeek', '{{viewsThisWeek}}', id FROM notification_templates WHERE template = 'WEEKLY-DIGEST';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'newMessages', '{{newMessages}}', id FROM notification_templates WHERE template = 'WEEKLY-DIGEST';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'topReferrersHtml', '{{topReferrersHtml}}', id FROM notification_templates WHERE template = 'WEEKLY-DIGEST';

-- CONTACT-REPLY variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'profileName', '{{profileName}}', id FROM notification_templates WHERE template = 'CONTACT-REPLY';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'contactName', '{{contactName}}', id FROM notification_templates WHERE template = 'CONTACT-REPLY';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'replyMessage', '{{replyMessage}}', id FROM notification_templates WHERE template = 'CONTACT-REPLY';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'originalMessage', '{{originalMessage}}', id FROM notification_templates WHERE template = 'CONTACT-REPLY';

-- WELCOME-EMAIL variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'WELCOME-EMAIL';

-- TWO-FACTOR-ENABLED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'TWO-FACTOR-ENABLED';

-- TWO-FACTOR-DISABLED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'TWO-FACTOR-DISABLED';

-- EMAIL-CHANGED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'EMAIL-CHANGED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'newEmail', '{{newEmail}}', id FROM notification_templates WHERE template = 'EMAIL-CHANGED';
