-- Enhanced email chrome (icon badge per template, mobile media query) applied to all
-- existing templates, plus 7 new templates covering previously-silent events:
-- GitHub connect/sync-failure, account status change, role change, account deletion,
-- portfolio domain change, and automatic testimonial-request invites.

UPDATE notification_templates SET
    subject = 'Your Verification Code — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128272;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Verify Your Email</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Use the code below to verify your email address. It expires in <strong>{{expiryMinutes}} minutes</strong>.</p><div style="text-align:center;margin:0 0 24px"><div style="display:inline-block;background:#ecfdf5;border:1.5px dashed #059669;border-radius:12px;padding:18px 36px"><span style="font-size:34px;font-weight:800;letter-spacing:10px;color:#047857">{{otp}}</span></div></div><p style="color:#9ca3af;font-size:13px;margin:0;">Did not request this code? You can safely ignore this email.</p></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'OTP-VERIFICATION';

UPDATE notification_templates SET
    subject = 'Reset Your Password — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128273;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Reset Your Password</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{name}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">We received a request to reset your password. Click the button below to choose a new one.</p><div style="text-align:center;margin:0 0 4px"><a href="{{resetLink}}" style="display:inline-block;background:#059669;color:#ffffff;text-decoration:none;padding:13px 30px;border-radius:10px;font-weight:700;font-size:14px">Reset Password</a></div><div style="height:20px"></div><p style="color:#6b7280;font-size:13px;margin:0 0 4px;">Button not working? Paste this link into your browser:</p><p style="font-size:13px;word-break:break-all;margin:0 0 20px"><a href="{{resetLink}}" style="color:#059669">{{resetLink}}</a></p><p style="color:#9ca3af;font-size:13px;margin:0;">This link expires in 30 minutes. Did not request this? You can safely ignore this email.</p></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'FORGOT-PASSWORD-TOKEN';

UPDATE notification_templates SET
    subject = 'New Message from {{senderName}} — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128235;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">New Portfolio Message</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{profileName}}</strong>, someone reached out through your portfolio contact form.</p><table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e5e7eb;border-radius:10px;overflow:hidden;font-size:14px"><tr><td style="padding:12px 16px;font-weight:600;color:#374151;background:#f9fafb;width:100px;border-bottom:1px solid #e5e7eb">From</td><td style="padding:12px 16px;color:#374151;border-bottom:1px solid #e5e7eb">{{senderName}}</td></tr><tr><td style="padding:12px 16px;font-weight:600;color:#374151;background:#f9fafb;border-bottom:1px solid #e5e7eb">Email</td><td style="padding:12px 16px;border-bottom:1px solid #e5e7eb"><a href="mailto:{{senderEmail}}" style="color:#059669">{{senderEmail}}</a></td></tr><tr><td style="padding:12px 16px;font-weight:600;color:#374151;background:#f9fafb;border-bottom:1px solid #e5e7eb">Phone</td><td style="padding:12px 16px;color:#374151;border-bottom:1px solid #e5e7eb">{{senderPhone}}</td></tr><tr><td style="padding:12px 16px;font-weight:600;color:#374151;background:#f9fafb;vertical-align:top">Message</td><td style="padding:12px 16px;color:#374151">{{message}}</td></tr></table></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">Sent via PortfoliosBuilder</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'CONTACT-US';

UPDATE notification_templates SET
    subject = 'New Testimonial Submitted — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#11088;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">New Testimonial Received</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 8px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;"><strong>{{requesterName}}</strong> just submitted a testimonial for your portfolio.</p><div style="background:#f9fafb;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#374151;font-size:13px;margin:0">&quot;{{message}}&quot;</p></div><div style="text-align:center;margin:0 0 4px"><a href="https://admin.portfoliosbuilder.com/testimonials" style="display:inline-block;background:#059669;color:#ffffff;text-decoration:none;padding:13px 30px;border-radius:10px;font-weight:700;font-size:14px">Review Testimonial</a></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">Log in to your admin panel to approve or reject this testimonial.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'TESTIMONIAL-SUBMITTED';

UPDATE notification_templates SET
    subject = 'Your Portfolio — Weekly Summary',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128202;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Hi, {{fullName}}</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Here is what happened on your portfolio this week:</p><table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 28px"><tr><td width="48%" style="padding:18px;text-align:center;background:#f9fafb;border-radius:10px;border:1px solid #e5e7eb"><p style="font-size:30px;font-weight:800;color:#059669;margin:0">{{viewsThisWeek}}</p><p style="font-size:13px;color:#6b7280;margin:4px 0 0">Portfolio Views</p></td><td width="4%">&nbsp;</td><td width="48%" style="padding:18px;text-align:center;background:#f9fafb;border-radius:10px;border:1px solid #e5e7eb"><p style="font-size:30px;font-weight:800;color:#059669;margin:0">{{newMessages}}</p><p style="font-size:13px;color:#6b7280;margin:4px 0 0">New Messages</p></td></tr></table><h3 style="font-size:14px;color:#374151;margin:0 0 12px">Top Traffic Sources</h3><table width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid #e5e7eb">{{topReferrersHtml}}</table></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">To stop receiving these emails, turn off Weekly Digest in your admin profile settings.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'WEEKLY-DIGEST';

UPDATE notification_templates SET
    subject = 'Re: Your message to {{profileName}} — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128172;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">You Have a Reply</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{contactName}}</strong>, <strong>{{profileName}}</strong> replied to your message.</p><div style="background:#ecfdf5;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#065f46;font-size:13px;margin:0">{{replyMessage}}</p></div><p style="color:#9ca3af;font-size:11px;margin:0 0 8px;text-transform:uppercase;letter-spacing:1px;">Your original message</p><p style="color:#6b7280;font-size:13px;line-height:1.6;white-space:pre-wrap;margin:0">{{originalMessage}}</p></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">Sent via PortfoliosBuilder</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'CONTACT-REPLY';

UPDATE notification_templates SET
    subject = 'Your Password Was Changed — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128274;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Password Changed</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">This is a confirmation that your PortfoliosBuilder password was changed on <strong>{{changedAt}}</strong>.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#7f1d1d;font-size:13px;margin:0">If you did not make this change, reset your password immediately and contact support.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'PASSWORD-CHANGED';

UPDATE notification_templates SET
    subject = 'Two-Factor Authentication Enabled — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128737;&#65039;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">2FA Enabled</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Two-factor authentication was just turned on for your account. You will now need an authenticator code every time you sign in.</p><div style="background:#ecfdf5;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#065f46;font-size:13px;margin:0">If you did not make this change, contact support immediately.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'TWO-FACTOR-ENABLED';

UPDATE notification_templates SET
    subject = 'Two-Factor Authentication Disabled — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#9888;&#65039;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">2FA Disabled</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Two-factor authentication was just turned off for your account. Your account is less secure without it.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#7f1d1d;font-size:13px;margin:0">If you did not make this change, contact support immediately.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'TWO-FACTOR-DISABLED';

UPDATE notification_templates SET
    subject = 'Your Account Email Was Changed — PortfoliosBuilder',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#9993;&#65039;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Email Address Changed</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Your account email was changed to <strong>{{newEmail}}</strong>. You are receiving this at your previous address as a security notice.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#7f1d1d;font-size:13px;margin:0">If you did not make this change, contact support immediately.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'EMAIL-CHANGED';

UPDATE notification_templates SET
    subject = 'Welcome to PortfoliosBuilder, {{fullName}}!',
    message_body = '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#127881;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Welcome, {{fullName}}</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Your email is verified and your account is ready to go.</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Here is what to do next:</p><table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 28px"><tr><td style="padding:10px 0;color:#374151;font-size:14px">1. Add your experience, skills, and projects</td></tr><tr><td style="padding:10px 0;color:#374151;font-size:14px;border-top:1px solid #f3f4f6">2. Pick a theme that matches your style</td></tr><tr><td style="padding:10px 0;color:#374151;font-size:14px;border-top:1px solid #f3f4f6">3. Publish and share your portfolio link</td></tr></table><div style="text-align:center;margin:0 0 4px"><a href="https://admin.portfoliosbuilder.com/dashboard" style="display:inline-block;background:#059669;color:#ffffff;text-decoration:none;padding:13px 30px;border-radius:10px;font-weight:700;font-size:14px">Go to Dashboard</a></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>'
WHERE template = 'WELCOME-EMAIL';

INSERT INTO notification_templates (template, subject, message_body, is_email, is_sms, is_whatsapp) VALUES
(
    'GITHUB-CONNECTED',
    'GitHub Connected — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128279;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">GitHub Connected</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Your GitHub account <strong>@{{githubUsername}}</strong> is now connected. We are syncing your pinned repositories and contribution stats now — this usually takes less than a minute.</p><div style="background:#ecfdf5;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#065f46;font-size:13px;margin:0">Stats refresh automatically every 6 hours. You can pick which repos show on your portfolio from the GitHub Integration tab.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'GITHUB-SYNC-FAILED',
    'GitHub Sync Failed — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#9888;&#65039;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">GitHub Sync Failed</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">We were not able to sync your GitHub repositories during the last scheduled update. This usually means your GitHub access was revoked or expired.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#7f1d1d;font-size:13px;margin:0">Reconnect your GitHub account from the GitHub Integration tab in your dashboard to resume syncing.</p></div><div style="text-align:center;margin:0 0 4px"><a href="https://admin.portfoliosbuilder.com/github-integration" style="display:inline-block;background:#059669;color:#ffffff;text-decoration:none;padding:13px 30px;border-radius:10px;font-weight:700;font-size:14px">Reconnect GitHub</a></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'ACCOUNT-STATUS-CHANGED',
    'Your Account Status Has Changed — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128100;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Account Status Updated</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Your PortfoliosBuilder account status was updated to <strong>{{status}}</strong>.</p><div style="background:#ecfdf5;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#065f46;font-size:13px;margin:0">If you believe this is a mistake, please contact support.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'PORTFOLIO-DOMAIN-UPDATED',
    'Your Portfolio Link Was Updated — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#127760;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Portfolio Link Updated</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Your public portfolio link was updated to:</p><p style="text-align:center;margin:0 0 24px"><a href="{{domainUrl}}" style="color:#059669;font-weight:700;font-size:15px;word-break:break-all">{{domainUrl}}</a></p><div style="background:#ecfdf5;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#065f46;font-size:13px;margin:0">Any previously shared links using your old address will no longer work. Update your resume, social profiles, and email signature with the new link.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'TESTIMONIAL-REQUEST-INVITE',
    '{{ownerName}} would love your feedback — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128140;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">A Testimonial Request</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{requesterName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;"><strong>{{ownerName}}</strong> would really appreciate a short testimonial about your experience working together. It only takes a couple of minutes.</p><div style="text-align:center;margin:0 0 4px"><a href="{{shareUrl}}" style="display:inline-block;background:#059669;color:#ffffff;text-decoration:none;padding:13px 30px;border-radius:10px;font-weight:700;font-size:14px">Write a Testimonial</a></div><div style="height:12px"></div><p style="color:#9ca3af;font-size:12px;margin:0;">This link is personal to you and expires in a few weeks.</p></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">Sent on behalf of {{ownerName}} via PortfoliosBuilder</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'ROLE-CHANGED',
    'Your Account Role Has Changed — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128081;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Role Updated</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Your PortfoliosBuilder account role was changed from <strong>{{oldRole}}</strong> to <strong>{{newRole}}</strong>.</p><div style="background:#ecfdf5;border-left:4px solid #059669;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#065f46;font-size:13px;margin:0">This may change what you can see and do in your admin panel. If you believe this is a mistake, please contact support.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
),
(
    'ACCOUNT-DELETED',
    'Your Account Has Been Deleted — PortfoliosBuilder',
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>@media only screen and (max-width:600px){.email-container{width:100% !important}.email-body{padding:28px 20px !important}}</style></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:-apple-system,Segoe UI,Roboto,sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 16px"><tr><td align="center"><table class="email-container" width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:560px"><tr><td style="background:linear-gradient(135deg,#059669,#047857);padding:34px 32px;text-align:center"><table cellpadding="0" cellspacing="0" style="margin:0 auto 14px"><tr><td style="width:46px;height:46px;border-radius:13px;background:rgba(255,255,255,0.16);text-align:center;vertical-align:middle;font-size:22px;line-height:46px">&#128465;&#65039;</td></tr></table><p style="color:#d1fae5;font-size:11px;letter-spacing:2px;margin:0 0 8px;text-transform:uppercase;font-weight:700">PortfoliosBuilder</p><h1 style="color:#fff;font-size:21px;margin:0;font-weight:800">Account Deleted</h1></td></tr><tr><td class="email-body" style="padding:36px 32px"><p style="color:#374151;font-size:15px;margin:0 0 20px;">Hi <strong>{{fullName}}</strong>,</p><p style="color:#374151;font-size:15px;margin:0 0 20px;">Your PortfoliosBuilder account and public portfolio have been deactivated. Your data is retained for a limited period in case this was a mistake.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;border-radius:8px;padding:16px 20px;margin:0 0 20px"><p style="color:#7f1d1d;font-size:13px;margin:0">If you did not request this or would like to restore your account, contact support as soon as possible.</p></div></td></tr><tr><td style="padding:20px 32px;border-top:1px solid #f3f4f6;text-align:center"><p style="color:#9ca3af;font-size:12px;margin:0">This is an automated message from PortfoliosBuilder.</p></td></tr></table></td></tr></table></body></html>',
    1, 0, 0
);

-- GITHUB-CONNECTED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'GITHUB-CONNECTED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'githubUsername', '{{githubUsername}}', id FROM notification_templates WHERE template = 'GITHUB-CONNECTED';

-- GITHUB-SYNC-FAILED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'GITHUB-SYNC-FAILED';

-- ACCOUNT-STATUS-CHANGED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'ACCOUNT-STATUS-CHANGED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'status', '{{status}}', id FROM notification_templates WHERE template = 'ACCOUNT-STATUS-CHANGED';

-- PORTFOLIO-DOMAIN-UPDATED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'PORTFOLIO-DOMAIN-UPDATED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'domainUrl', '{{domainUrl}}', id FROM notification_templates WHERE template = 'PORTFOLIO-DOMAIN-UPDATED';

-- TESTIMONIAL-REQUEST-INVITE variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'requesterName', '{{requesterName}}', id FROM notification_templates WHERE template = 'TESTIMONIAL-REQUEST-INVITE';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'ownerName', '{{ownerName}}', id FROM notification_templates WHERE template = 'TESTIMONIAL-REQUEST-INVITE';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'shareUrl', '{{shareUrl}}', id FROM notification_templates WHERE template = 'TESTIMONIAL-REQUEST-INVITE';

-- ROLE-CHANGED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'ROLE-CHANGED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'oldRole', '{{oldRole}}', id FROM notification_templates WHERE template = 'ROLE-CHANGED';
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'newRole', '{{newRole}}', id FROM notification_templates WHERE template = 'ROLE-CHANGED';

-- ACCOUNT-DELETED variables
INSERT INTO notification_template_variables (variable_name, html_content, template_id)
SELECT 'fullName', '{{fullName}}', id FROM notification_templates WHERE template = 'ACCOUNT-DELETED';
